/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductCategory = IDL.Variant({
  'ragiChips' : IDL.Null,
  'jowarPuffs' : IDL.Null,
  'comboPack' : IDL.Null,
  'milletCookies' : IDL.Null,
});
export const ProductSize = IDL.Record({
  'name' : IDL.Text,
  'stock' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(ProductSize),
  'category' : ProductCategory,
});
export const SubscriptionPlan = IDL.Record({
  'name' : IDL.Text,
  'durationMonths' : IDL.Nat,
  'description' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
});
export const Time = IDL.Int;
export const Testimonial = IDL.Record({
  'customerName' : IDL.Text,
  'productId' : IDL.Nat,
  'feedback' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'upi' : IDL.Null,
  'card' : IDL.Null,
});

export const idlService = IDL.Service({
  'addToCart' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
  'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
  'getProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getSubscriptionPlans' : IDL.Func([], [IDL.Vec(SubscriptionPlan)], ['query']),
  'getTestimonials' : IDL.Func([IDL.Nat], [IDL.Vec(Testimonial)], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, PaymentMethod],
      [IDL.Record({ 'orderId' : IDL.Nat, 'totalAmount' : IDL.Nat })],
      [],
    ),
  'subscribeNewsletter' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductCategory = IDL.Variant({
    'ragiChips' : IDL.Null,
    'jowarPuffs' : IDL.Null,
    'comboPack' : IDL.Null,
    'milletCookies' : IDL.Null,
  });
  const ProductSize = IDL.Record({
    'name' : IDL.Text,
    'stock' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(ProductSize),
    'category' : ProductCategory,
  });
  const SubscriptionPlan = IDL.Record({
    'name' : IDL.Text,
    'durationMonths' : IDL.Nat,
    'description' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Testimonial = IDL.Record({
    'customerName' : IDL.Text,
    'productId' : IDL.Nat,
    'feedback' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  const PaymentMethod = IDL.Variant({
    'cod' : IDL.Null,
    'upi' : IDL.Null,
    'card' : IDL.Null,
  });
  
  return IDL.Service({
    'addToCart' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [], []),
    'getCartTotal' : IDL.Func([], [IDL.Nat], ['query']),
    'getProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlan)],
        ['query'],
      ),
    'getTestimonials' : IDL.Func([IDL.Nat], [IDL.Vec(Testimonial)], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, PaymentMethod],
        [IDL.Record({ 'orderId' : IDL.Nat, 'totalAmount' : IDL.Nat })],
        [],
      ),
    'subscribeNewsletter' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };