/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type PaymentMethod = { 'cod' : null } |
  { 'upi' : null } |
  { 'card' : null };
export interface Product {
  'name' : string,
  'isAvailable' : boolean,
  'description' : string,
  'sizes' : Array<ProductSize>,
  'category' : ProductCategory,
}
export type ProductCategory = { 'ragiChips' : null } |
  { 'jowarPuffs' : null } |
  { 'comboPack' : null } |
  { 'milletCookies' : null };
export interface ProductSize {
  'name' : string,
  'stock' : bigint,
  'price' : bigint,
}
export interface SubscriptionPlan {
  'name' : string,
  'durationMonths' : bigint,
  'description' : string,
  'benefits' : Array<string>,
  'price' : bigint,
}
export interface Testimonial {
  'customerName' : string,
  'productId' : bigint,
  'feedback' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'addToCart' : ActorMethod<[bigint, string, bigint], undefined>,
  'getCartTotal' : ActorMethod<[], bigint>,
  'getProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'getSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlan>>,
  'getTestimonials' : ActorMethod<[bigint], Array<Testimonial>>,
  'placeOrder' : ActorMethod<
    [string, string, string, string, PaymentMethod],
    { 'orderId' : bigint, 'totalAmount' : bigint }
  >,
  'subscribeNewsletter' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];